TBIBankApp/Controllers/EmailController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.Logging;
using TBIApp.Data.Models;
using TBIApp.Services.Services.Contracts;
using TBIBankApp.Hubs;
using TBIBankApp.Mappers.Contracts;
using TBIBankApp.Models.Emails;

namespace TBIBankApp.Controllers
{
    [Authorize]
    [AutoValidateAntiforgeryToken]
    public class EmailController : Controller
    {
        private readonly IEmailService emailService;
        private readonly IEmailViewModelMapper emailMapper;
        private readonly UserManager<User> userManager;
        private readonly ILogger<EmailController> logger;
        private readonly IHubContext<NotificationHub> hubContext;
        private readonly IApplicationService applicationService;

        public EmailController(IEmailService emailService, 
                               IEmailViewModelMapper emailMapper, 
                               UserManager<User> userManager, 
                               IHubContext<NotificationHub> hubContext, 
                               IApplicationService applicationService,
                               ILogger<EmailController> logger)
        {
            this.hubContext = hubContext ?? throw new ArgumentNullException(nameof(hubContext));
            this.applicationService = applicationService ?? throw new ArgumentNullException(nameof(applicationService));
            this.emailService = emailService ?? throw new ArgumentNullException(nameof(emailService));
            this.emailMapper = emailMapper ?? throw new ArgumentNullException(nameof(emailMapper));
            this.userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> ListEmailsAsync(int id, string emailStatus)
        {

            try
            {
                var newEmailStatus = (EmailStatusesEnum)Enum.Parse(typeof(EmailStatusesEnum), emailStatus, true);

                var result = await GetEmailsAsync(id, newEmailStatus);

                string status = "List" + newEmailStatus.ToString() + "Emails";

                return View($"{status}", result);
            }
            catch (Exception ex)
            {
                this.logger.LogError($"Error occurred while trying to get emails for page {id} and status {emailStatus} at {DateTime.Now}.", ex);

            }

            return BadRequest();

        }

        [HttpGet]
        public async Task<IActionResult> ChangeStatusAsync(string id, string status)
        {
            if (!ModelState.IsValid) return BadRequest();

            var email = await this.emailService.GetEmailAsync(id);
            var oldstatus = email.Status;
            try
            {
                var newEmailStatus = (EmailStatusesEnum)Enum.Parse(typeof(EmailStatusesEnum), status, true);
                if ((oldstatus == EmailStatusesEnum.Open||oldstatus==EmailStatusesEnum.Closed) && status.ToLower() == "new")
                {
                    await this.applicationService.RemoveAsync(id);
                }
                var currentUser = await this.userManager.GetUserAsync(User);


                await this.emailService.ChangeStatusAsync(id, newEmailStatus, currentUser);

                await this.hubContext.Clients.All.SendAsync("UpdateChart", status, oldstatus);
            }
            catch (Exception ex)
            {
                this.logger.LogError($"Error occurred while trying to change status of email {id} to status {status}", ex);
            }

            return Ok();
        }

        public async Task<EmailListModel> GetEmailsAsync(int Id, EmailStatusesEnum status)
        {
            if (Id == 0) { Id = 1; }

            var currentUser = await userManager.GetUserAsync(User);
            var listEmailDTOS = await this.emailService.GetCurrentPageEmailsAsync(Id, status, currentUser);


            var result = new EmailListModel()
            {
                Status = status.ToString(),
                EmailViewModels = this.emailMapper.MapFrom(listEmailDTOS),
                CurrentUser = currentUser,
                PreviousPage = Id == 1 ? 1 : Id - 1,
                CurrentPage = Id,
                NextPage = Id + 1,
                LastPage = await this.emailService.GetEmailsPagesByTypeAsync(status)
            };

            return result;

        }

        [HttpGet]
        public async Task<IActionResult> IsItOpenAsync(string id)
        {
            if (await emailService.IsOpenAsync(id))
            {
                return new JsonResult("true");
            }

            await this.emailService.LockButtonAsync(id);

            await this.hubContext.Clients.All.SendAsync("LockButton", id);

            return new JsonResult("false");
        }

        [HttpGet]
        public async Task SetToEnableAsync(string id)
        {
            await this.emailService.UnLockButtonAsync(id);
            await this.hubContext.Clients.All.SendAsync("UnlockButton", id);
        }
    }
}

TBIBankApp/Views/Shared/BadRequest.cshtml
<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgjFENRI1sYecM_G9OLHplp2F7WcCazdjTyVubtHgZNbMlvjAANw&s" />

TBIBankApp/Views/Shared/PageNotFound.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link href="~/css/error404.css" rel="stylesheet" />
</head>
<body>
    <div class="wrapper">
        <div id="page404">
            <button id="BackToDashboard" class="btn btn-light">Back To Dashboard</button>
        </div>
    </div>
</body>
</html>


<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/BackToDashboard.js"></script>

TBIBankApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html id="html">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TBIBankApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="icon" type="image/png" href="images/icons/favicon.ico" />
        <link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="fonts/iconic/css/material-design-iconic-font.min.css">
        <link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
        <link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
        <link rel="stylesheet" type="text/css" href="vendor/animsition/css/animsition.min.css">
        <link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
        <link rel="stylesheet" type="text/css" href="vendor/daterangepicker/daterangepicker.css">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="icon" type="image/ico" href="images/icons/favicon.ico" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="~/css/util.css">
    <link rel="stylesheet" href="~/css/style.css" />

    @RenderSection("Styles", required: false)
    <link rel="stylesheet" type="text/css" href="~/css/nunito-font.css">
</head>
<body>

    <header class="header">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                <img src="~/images/logo-tbi.png" />
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Dashboard">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="listnew" asp-controller="Email" asp-action="ListEmailsAsync" asp-route-emailStatus="InvalidApplication">Invalid</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="listnotreviewd" asp-controller="Email" asp-action="ListEmailsAsync" asp-route-emailStatus="NotReviewed">Not Reviewed</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="listinvalid" asp-controller="Email" asp-action="ListEmailsAsync" asp-route-emailStatus="New">New</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="listopen" asp-controller="Email" asp-action="ListEmailsAsync" asp-route-emailStatus="Open">Opened</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="listclosed" asp-controller="Email" asp-action="ListEmailsAsync" asp-route-emailStatus="Closed">Closed</a>
                    </li>
                    @if (User.IsInRole("Manager") || User.IsInRole("Administrator"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Manager" asp-action="Register">Register</a>
                        </li>

                    }
                    @if (User.IsInRole("Administrator"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Administrator" asp-action="Index">Administrator Panel</a>
                        </li>
                    }

                </ul>
                <partial name="_LoginPartial" />



            </div>

        </nav>
    </header>

    <div>
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3" id="main-container">
            @RenderBody()
        </main>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/vendor/animsition/js/animsition.min.js"></script>
        <script src="~/vendor/bootstrap/js/popper.js"></script>
        <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
        <script src="~/vendor/select2/select2.min.js"></script>
        <script src="~/vendor/daterangepicker/moment.min.js"></script>
        <script src="~/vendor/daterangepicker/daterangepicker.js"></script>
        <script src="~/vendor/countdowntime/countdowntime.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/autologout.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>